### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iviejo** [novus-afk/TRANSIENT-1D-Unsteady-State-Diffusion-solver-python#1]
The code has serveral errors:

- It is only valid for grid points =5
- Implicit solver not take into account te
- ...

**Comment by novus-afk** [comment]
>

**Comment by yahya-ansariii** [comment]
> 
Thanks for pointing out the errors, will check and update.
Could you specify the line number in code?

**Comment by iviejo** [comment]
To be valid for different discretization the line:
df = pd.DataFrame(columns=["Node: 1", "Node: 2",
                  "Node: 3", "Node: 4", "Node: 5"])

Should be:
header=[]
for i in range(n):
    header.append("Node: %i" %i)
df = pd.DataFrame(columns=header)


For the other error, I have not clear because I don't know the details of TDMA implementation. Tha fact for the implicit method you could solve directly a linear solver problem Ax=b

**Comment by yahya-ansariii** [comment]
Fixed number of nodes issue. If any other errors are found feel free to open a new issue.
